CREATE TABLE HOSPITAL (
    HOSPITAL_COD NUMBER(2) NOT NULL,
    NOMBRE VARCHAR2(10) NOT NULL,
    DIRECCION VARCHAR2(20) NOT NULL,
    TELEFONO VARCHAR2(8) NOT NULL,
    NUM_CAMA NUMBER(3) NOT NULL,
    CONSTRAINT hospital_pk PRIMARY KEY (HOSPITAL_COD)
);

CREATE TABLE SALA (
    HOSPITAL_COD NUMBER(2) NOT NULL,
    SALA_COD NUMBER(2) NOT NULL,
    NOMBRE VARCHAR2(20),
    NUM_CAMA NUMBER(3)
);

CREATE TABLE PLANTILLA (
    	HOSPITAL_COD NUMBER(2) NOT NULL,
    	SALA_COD NUMBER(2) NOT NULL,
    	EMPLEADO_NO NUMBER(4) NOT NULL,
	APELLIDO VARCHAR2(15),
	FUNCION VARCHAR2(10),
	TURNO VARCHAR2(1),
	SALARIO NUMBER(10),
        CONSTRAINT plantilla_pk PRIMARY KEY (EMPLEADO_NO)
);

CREATE TABLE OCUPACION (
	INSCRIPCION  NUMBER(5) NOT NULL,
	HOSPITAL_COD NUMBER(2) NOT NULL,
	SALA_COD  NUMBER(2) NOT NULL,
	CAMA NUMBER(4),
	CONSTRAINT ocupacion_pk PRIMARY KEY (INSCRIPCION)
);

CREATE TABLE DOCTOR (
	HOSPITAL_COD  NUMBER(2) NOT NULL,
	DOCTOR_NO  NUMBER(3) NOT NULL,
	APELLIDO VARCHAR2(13),
	ESPECIALIDAD VARCHAR2(16),
	CONSTRAINT doctor_pk PRIMARY KEY (DOCTOR_NO)		
);

CREATE TABLE ENFERMO (
	INSCRIPCION  NUMBER(5) NOT NULL,
	APELLIDO VARCHAR2(15),
	DIRECCION VARCHAR2(20),
	FECHA_NAC DATE,
	S VARCHAR2(1),
	NSS NUMBER(9)
);

CREATE TABLE EMPLEADO (
	EMP_NO NUMBER(4) NOT NULL,
	APELLIDO VARCHAR2(10),
	OFICIO VARCHAR2(10),
	DIR NUMBER(4),
	FECHA_ALTA DATE,
	SALARIO NUMBER(10),
	COMISION NUMBER(10),
	DEPT_NO NUMBER(2) NOT NULL,
	CONSTRAINT empleado_pk PRIMARY KEY (EMP_NO)
);

CREATE TABLE DEPARTAMENTO(
	DEPT_NO NUMBER(2) NOT NULL,
	DNOMBRE VARCHAR2(14),
	LOC VARCHAR2(14),
	CONSTRAINT departamento_pk PRIMARY KEY (DEPT_NO)
);


 INSERT ALL
  
    INTO HOSPITAL (HOSPITAL_COD, NOMBRE, DIRECCION, TELEFONO, NUM_CAMA) VALUES (13, 'Provincial', 'O Donell 50', '964-4264', 502)
    INTO HOSPITAL (HOSPITAL_COD, NOMBRE, DIRECCION, TELEFONO, NUM_CAMA) VALUES (18, 'General', 'Atocha s/n', '595-3111', 987)
    INTO HOSPITAL (HOSPITAL_COD, NOMBRE, DIRECCION, TELEFONO, NUM_CAMA) VALUES (22, 'La Paz', 'Castellana 1000', '923-5411', 412)
    INTO HOSPITAL (HOSPITAL_COD, NOMBRE, DIRECCION, TELEFONO, NUM_CAMA) VALUES (45, 'San Carlos', 'Ciudad Universitaria', '597-1500', 845)
  
    INTO SALA (HOSPITAL_COD,SALA_COD, NOMBRE, NUM_CAMA) VALUES(13, 3, 'Cuidados Intensivos', 21)
    INTO SALA (HOSPITAL_COD,SALA_COD, NOMBRE, NUM_CAMA) VALUES(13, 6, 'Psiquiátrico', 67)
    INTO SALA (HOSPITAL_COD,SALA_COD, NOMBRE, NUM_CAMA) VALUES(18, 3, 'Cuidados Intensivos', 10)
    INTO SALA (HOSPITAL_COD,SALA_COD, NOMBRE, NUM_CAMA) VALUES(18, 4, 'Cardiología', 53)
    INTO SALA (HOSPITAL_COD,SALA_COD, NOMBRE, NUM_CAMA) VALUES(22, 1, 'Recuperación', 10)
    INTO SALA (HOSPITAL_COD,SALA_COD, NOMBRE, NUM_CAMA) VALUES(22, 6, 'Psiquiátrico', 118)
    INTO SALA (HOSPITAL_COD,SALA_COD, NOMBRE, NUM_CAMA) VALUES(22, 2, 'Maternidad', 34)
    INTO SALA (HOSPITAL_COD,SALA_COD, NOMBRE, NUM_CAMA) VALUES(45, 4, 'Cardiología', 55)
    INTO SALA (HOSPITAL_COD,SALA_COD, NOMBRE, NUM_CAMA) VALUES(45, 1, 'Recuperación', 13)
    INTO SALA (HOSPITAL_COD,SALA_COD, NOMBRE, NUM_CAMA) VALUES(45, 2, 'Maternidad', 24)
  
    INTO PLANTILLA (HOSPITAL_COD,SALA_COD, EMPLEADO_NO, APELLIDO, FUNCION, TURNO, SALARIO) VALUES (13, 6, 3754, 'Diaz B.', 'Enfermera', 'T', 2262000)
    INTO PLANTILLA (HOSPITAL_COD,SALA_COD, EMPLEADO_NO, APELLIDO, FUNCION, TURNO, SALARIO) VALUES (13, 6, 3106, 'Hernandez J.','Enfermero', 'T', 2755000)
    INTO PLANTILLA (HOSPITAL_COD,SALA_COD, EMPLEADO_NO, APELLIDO, FUNCION, TURNO, SALARIO) VALUES (18, 4, 6357, 'Karplus W.' ,'Interno', 'T', 3379000)
    INTO PLANTILLA (HOSPITAL_COD,SALA_COD, EMPLEADO_NO, APELLIDO, FUNCION, TURNO, SALARIO) VALUES (22, 6, 1009, 'Higueras D.', 'Enfermera', 'T', 2005000)
    INTO PLANTILLA (HOSPITAL_COD,SALA_COD, EMPLEADO_NO, APELLIDO, FUNCION, TURNO, SALARIO) VALUES (22, 6, 8422, 'Bocina G.', 'Enfermero', 'M', 1638000)
    INTO PLANTILLA (HOSPITAL_COD,SALA_COD, EMPLEADO_NO, APELLIDO, FUNCION, TURNO, SALARIO) VALUES (22, 2, 9901, 'NuÑez C.' ,'Interno', 'M', 2210000)
    INTO PLANTILLA (HOSPITAL_COD,SALA_COD, EMPLEADO_NO, APELLIDO, FUNCION, TURNO, SALARIO) VALUES (22, 1, 6065, 'Rivera G.','Enfermera', 'N', 1626000)
    INTO PLANTILLA (HOSPITAL_COD,SALA_COD, EMPLEADO_NO, APELLIDO, FUNCION, TURNO, SALARIO) VALUES (22, 1, 7379, 'Carlos R.', 'Enfermera', 'T', 2119000)
    INTO PLANTILLA (HOSPITAL_COD,SALA_COD, EMPLEADO_NO, APELLIDO, FUNCION, TURNO, SALARIO) VALUES (45, 4, 1280, 'Amigo R.', 'Interno', 'N', 2210000)
    INTO PLANTILLA (HOSPITAL_COD,SALA_COD, EMPLEADO_NO, APELLIDO, FUNCION, TURNO, SALARIO) VALUES (45, 1, 8526, 'Frank H.', 'Enfermera', 'T', 2522000)
  
    INTO OCUPACION (INSCRIPCION, HOSPITAL_COD, SALA_COD, CAMA) VALUES (10995, 13, 3, 1)
    INTO OCUPACION (INSCRIPCION, HOSPITAL_COD, SALA_COD, CAMA) VALUES (14024, 13, 3, 3)
    INTO OCUPACION (INSCRIPCION, HOSPITAL_COD, SALA_COD, CAMA) VALUES (36658, 18, 4, 1)
    INTO OCUPACION (INSCRIPCION, HOSPITAL_COD, SALA_COD, CAMA) VALUES (38702, 18, 4, 2)
    INTO OCUPACION (INSCRIPCION, HOSPITAL_COD, SALA_COD, CAMA) VALUES (39217, 22, 6, 1)
    INTO OCUPACION (INSCRIPCION, HOSPITAL_COD, SALA_COD, CAMA) VALUES (59076, 22, 6, 2)
    INTO OCUPACION (INSCRIPCION, HOSPITAL_COD, SALA_COD, CAMA) VALUES (63827, 22, 6, 3)
    INTO OCUPACION (INSCRIPCION, HOSPITAL_COD, SALA_COD, CAMA) VALUES (64823, 22, 2, 1)
    INTO OCUPACION (INSCRIPCION, HOSPITAL_COD, SALA_COD, CAMA) VALUES (18004, 13, 3, 2)
 
    INTO DOCTOR (HOSPITAL_COD, DOCTOR_NO, APELLIDO, ESPECIALIDAD) VALUES (13, 435, 'Lopez A.', 'Cardiología')
    INTO DOCTOR (HOSPITAL_COD, DOCTOR_NO, APELLIDO, ESPECIALIDAD) VALUES (18, 585, 'Miller G.', 'Ginecología')
    INTO DOCTOR (HOSPITAL_COD, DOCTOR_NO, APELLIDO, ESPECIALIDAD) VALUES (18, 982, 'Cajal R.', 'Cardiología')
    INTO DOCTOR (HOSPITAL_COD, DOCTOR_NO, APELLIDO, ESPECIALIDAD) VALUES (22, 453, 'Galo D.', 'Pediatría')
    INTO DOCTOR (HOSPITAL_COD, DOCTOR_NO, APELLIDO, ESPECIALIDAD) VALUES (22, 398, 'Best K.', 'Urología')
    INTO DOCTOR (HOSPITAL_COD, DOCTOR_NO, APELLIDO, ESPECIALIDAD) VALUES (22, 386, 'Cabeza D.', 'Psiquiatría')
    INTO DOCTOR (HOSPITAL_COD, DOCTOR_NO, APELLIDO, ESPECIALIDAD) VALUES (45, 607, 'Niqo P.', 'Pediatría')
    INTO DOCTOR (HOSPITAL_COD, DOCTOR_NO, APELLIDO, ESPECIALIDAD) VALUES (45, 522, 'Adams C.', 'Neurología')

    INTO ENFERMO (INSCRIPCION, APELLIDO, DIRECCION, FECHA_NAC, S, NSS) VALUES (10995, 'Laguia M.', 'Recoletos 50', TO_DATE('1967-06-23', 'YYYY-MM-DD'), 'M', 280862482)
    INTO ENFERMO (INSCRIPCION, APELLIDO, DIRECCION, FECHA_NAC, S, NSS) VALUES (18004, 'Serrano V.', 'Alcala 12', TO_DATE('1960-05-21', 'YYYY-MM-DD'), 'F', 284991452)
    INTO ENFERMO (INSCRIPCION, APELLIDO, DIRECCION, FECHA_NAC, S, NSS) VALUES (14024, 'Fernandez M', 'Recoletos 50', TO_DATE('1967-06-23', 'YYYY-MM-DD'), 'F', 321790059)
    INTO ENFERMO (INSCRIPCION, APELLIDO, DIRECCION, FECHA_NAC, S, NSS) VALUES (36658, 'Domin S.', 'Mayor 71', TO_DATE('1942-01-01', 'YYYY-MM-DD'), 'M', 160657471)
    INTO ENFERMO (INSCRIPCION, APELLIDO, DIRECCION, FECHA_NAC, S, NSS) VALUES (38702, 'Neal R.', 'Orense 11', TO_DATE('1940-06-18', 'YYYY-MM-DD'), 'F', 380010217)
    INTO ENFERMO (INSCRIPCION, APELLIDO, DIRECCION, FECHA_NAC, S, NSS) VALUES (39217, 'Cervantes M.', 'Peron 38', TO_DATE('1952-02-29', 'YYYY-MM-DD'), 'M', 440294390)
    INTO ENFERMO (INSCRIPCION, APELLIDO, DIRECCION, FECHA_NAC, S, NSS) VALUES (59076, 'Miller G.', 'Lopez de Hoyos 2',TO_DATE('1945-09-16', 'YYYY-MM-DD'),'F', 311969044)
    INTO ENFERMO (INSCRIPCION, APELLIDO, DIRECCION, FECHA_NAC, S, NSS) VALUES (63827, 'Ruiz P.', 'Esquerdo 103', TO_DATE('1980-12-26', 'YYYY-MM-DD'), 'M', 100973253)
    INTO ENFERMO (INSCRIPCION, APELLIDO, DIRECCION, FECHA_NAC, S, NSS) VALUES (64823, 'Fraser A.', 'Soto 3',TO_DATE('1980-07-10', 'YYYY-MM-DD'), 'F', 285201776)
    INTO ENFERMO (INSCRIPCION, APELLIDO, DIRECCION, FECHA_NAC, S, NSS) VALUES (74835, 'Benitez E.', 'Argentina 5', TO_DATE('1957-10-05', 'YYYY-MM-DD'), 'M', 154811767)

    INTO EMPLEADO (EMP_NO, APELLIDO, OFICIO, DIR, FECHA_ALTA, SALARIO, COMISION, DEPT_NO) VALUES (7369, 'Sanchez','Empleado', 7902, TO_DATE('1980-12-17', 'YYYY-MM-DD'), 104000, NULL, 20)
    INTO EMPLEADO (EMP_NO, APELLIDO, OFICIO, DIR, FECHA_ALTA, SALARIO, COMISION, DEPT_NO) VALUES (7499, 'Arroyo', 'Vendedor', 7698, TO_DATE('1981-02-20', 'YYYY-MM-DD'),  208000, 39000, 30)
    INTO EMPLEADO (EMP_NO, APELLIDO, OFICIO, DIR, FECHA_ALTA, SALARIO, COMISION, DEPT_NO) VALUES (7521, 'Sala', 'Vendedor', 7698, TO_DATE('1981-02-22', 'YYYY-MM-DD'), 162500, 65000, 30)
    INTO EMPLEADO (EMP_NO, APELLIDO, OFICIO, DIR, FECHA_ALTA, SALARIO, COMISION, DEPT_NO) VALUES (7566, 'Jimenez', 'Director', 7839, TO_DATE('1981-04-02', 'YYYY-MM-DD'), 386750, NULL, 20)
    INTO EMPLEADO (EMP_NO, APELLIDO, OFICIO, DIR, FECHA_ALTA, SALARIO, COMISION, DEPT_NO) VALUES (7654, 'Arenas', 'Vendedor', 7698, TO_DATE('1981-09-28', 'YYYY-MM-DD'), 162500, 182000, 30)
    INTO EMPLEADO (EMP_NO, APELLIDO, OFICIO, DIR, FECHA_ALTA, SALARIO, COMISION, DEPT_NO) VALUES (7698, 'Negro', 'Director', 7839, TO_DATE('1981-05-01', 'YYYY-MM-DD'),   370500, NULL, 30)
    INTO EMPLEADO (EMP_NO, APELLIDO, OFICIO, DIR, FECHA_ALTA, SALARIO, COMISION, DEPT_NO) VALUES (7782, 'Cerezo','Director', 7839, TO_DATE('1981-06-09', 'YYYY-MM-DD'), 318500, NULL, 10)
    INTO EMPLEADO (EMP_NO, APELLIDO, OFICIO, DIR, FECHA_ALTA, SALARIO, COMISION, DEPT_NO) VALUES (7788, 'Gil', 'Analista', 7566, TO_DATE('1982-12-09', 'YYYY-MM-DD'), 390000, NULL, 20)
    INTO EMPLEADO (EMP_NO, APELLIDO, OFICIO, DIR, FECHA_ALTA, SALARIO, COMISION, DEPT_NO) VALUES (7839, 'Rey', 'Presidente', NULL, TO_DATE('1981-11-17', 'YYYY-MM-DD'), 650000,   NULL, 10)
    INTO EMPLEADO (EMP_NO, APELLIDO, OFICIO, DIR, FECHA_ALTA, SALARIO, COMISION, DEPT_NO) VALUES (7844, 'Tovar', 'Vendedor', 7698, TO_DATE('1981-09-08', 'YYYY-MM-DD'), 195000,   0, 30)
    INTO EMPLEADO (EMP_NO, APELLIDO, OFICIO, DIR, FECHA_ALTA, SALARIO, COMISION, DEPT_NO) VALUES (7876, 'Alonso', 'Empleado', 7788, TO_DATE('1983-01-12', 'YYYY-MM-DD'), 143000, NULL, 20)
    INTO EMPLEADO (EMP_NO, APELLIDO, OFICIO, DIR, FECHA_ALTA, SALARIO, COMISION, DEPT_NO) VALUES (7900, 'Jimeno', 'Empleado', 7698, TO_DATE('1981-12-03', 'YYYY-MM-DD'), 123500, NULL, 30)
    INTO EMPLEADO (EMP_NO, APELLIDO, OFICIO, DIR, FECHA_ALTA, SALARIO, COMISION, DEPT_NO) VALUES (7902, 'Fernandez','Analista', 7566, TO_DATE('1981-12-03', 'YYYY-MM-DD'), 390000, NULL, 20)
    INTO EMPLEADO (EMP_NO, APELLIDO, OFICIO, DIR, FECHA_ALTA, SALARIO, COMISION, DEPT_NO) VALUES (7934, 'Muñoz', 'Empleado', 7782, TO_DATE('1982-01-23', 'YYYY-MM-DD'), 169000,   NULL, 10)

    INTO DEPARTAMENTO(DEPT_NO, DNOMBRE, LOC) VALUES (10, 'CONTABILIDAD', 'MADRID')
    INTO DEPARTAMENTO(DEPT_NO, DNOMBRE, LOC) VALUES (20, 'INVESTIGACIÓN', 'BILBAO')
    INTO DEPARTAMENTO(DEPT_NO, DNOMBRE, LOC) VALUES (30, 'VENTAS', 'SEVILLA')
    INTO DEPARTAMENTO(DEPT_NO, DNOMBRE, LOC) VALUES (40, 'OPERACIONES', 'MALAGA')

SELECT * FROM dual;
